---
shared:
    shared_key: shared_val

modules:
    utils:
    report:
    ad_handler:

    # 主要功能模組
    login:
        username: kevin930321
        password: sy7428sy
    #    twofa: $twofa
    sign:
    answer:
    lottery:
        max_attempts: 50 
        max_parallel: 3
    del_mail:
        match:
            - title: "【勇者福利社】成功獲得抽獎資格通知信"
            - title: "動畫瘋獲獎通知"
    logout:

    discord:
        webhook: https://discord.com/api/webhooks/1165878055898726410/Mg8ZaGSFFQ9vGiYqa02muybUjF_p-rHtNxi_jiFC4vAva5bDR7t1TzLmg8dZGHGcZeOa

browser:
    type: webkit
    #type: firefox
    #type: chromium
    #type: chrome
    #type: msedge
    headless: true
    firefoxUserPrefs:
        dom.webaudio.enabled: false
        media.volume_scale: 0
        media.default_volume: 0
    # executablePath: /home/runner/.cache/ms-playwright/webkit-1869/pw_run.sh
