name: 下午的自動化

on:
    schedule:
        - cron: "30 4 * * *"
        
    workflow_dispatch:


jobs:
    automation:
        name: 自動化
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install Browser
              run: npm install
              run: npx playwright install
              #run: npx playwright install webkit --with-deps
              run: npx playwright install firefox #--with-deps
              #run: npx playwright install chromium --with-deps

            #- name: Install Bahamut Automation
              #run: npm install -g bahamut-automation 

            - name: Bahamut Automation
              run: docker run --rm -v "$(pwd)/config.yml:/config.yml" jacoblincool/bahamut-automation

            - uses: gautamkrishnar/keepalive-workflow@master