name: 下午的自動化

on:
    schedule:
        - cron: "30 4 * * *"
        
    workflow_dispatch:


jobs:
    automation:
        name: 自動化
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Create directory for downloaded browser
              run: sudo mkdir -p /root/.cache/ms-playwright/chromium-1015

            - name: Download browser ZIP file
              run: wget https://playwright.azureedge.net/builds/chromium/1015/chromium-linux.zip -O /root/.cache/ms-playwright/chromium-1015/chromium-linux.zip

            - name: Extract browser ZIP file
              run: unzip /root/.cache/ms-playwright/chromium-1015/chromium-linux.zip -d /root/.cache/ms-playwright/chromium-1015

            - name: Set executable path for browser
              run: export PLAYWRIGHT_CHROMIUM_PATH=/root/.cache/ms-playwright/chromium-1015/chrome-linux/chrome


            - name: Bahamut Automation
              run: docker run --rm -v "$(pwd)/config.yml:/config.yml" jacoblincool/bahamut-automation

            - uses: gautamkrishnar/keepalive-workflow@master
