name: 下午的自動化

on:
   # schedule:
       # - cron: "30 4 * * *"
        
    workflow_dispatch:


jobs:
    automation:
        name: 自動化
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Create directory for downloaded browser
              run: sudo mkdir -p /root/.cache/ms-playwright/firefox-1335

            - name: Download browser ZIP file
              run: |
               sudo wget https://playwright.azureedge.net/builds/firefox/1335/firefox-ubuntu-22.04.zip
 -O /root/.cache/ms-playwright/firefox-1335/firefox-ubuntu-22.04.zip
               sudo unzip /root/.cache/ms-playwright/firefox-1335/firefox-ubuntu-22.04.zip -d /root/.cache/ms-playwright/firefox-1335/

            - name: Set executable path for browser
              run: export PLAYWRIGHT_CHROMIUM_PATH=/root/.cache/ms-playwright/firefox-1335/firefox/firefox

            - name: Check Path
              run: sudo ls /root/.cache/ms-playwright/firefox-1335/firefox/firefox

            - name: Bahamut Automation
              run: docker run --rm -v "$(pwd)/config.yml:/config.yml" jacoblincool/bahamut-automation

            - uses: gautamkrishnar/keepalive-workflow@master
